# Descibes how multiple Docker containers work together
services:
  db:
    image: postgres:16-alpine
    container_name: myapp-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: myapp-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Optional overrides (if you want them instead of application-docker.yml)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
